M48
; DRILL file {KiCad (6.0.4)} date Mon Apr 11 16:33:45 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-11T16:33:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.6378Y-2.3444
X3.6399Y-5.7165
X7.2933Y-2.3465
X7.2933Y-5.7165
T0
M30
