M48
; DRILL file {KiCad (6.0.1)} date Thu Feb 10 21:15:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-10T21:15:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.8484Y-2.2814
X3.8505Y-5.1378
X7.2933Y-2.2835
X7.2933Y-5.1378
T0
M30
